import "./styles/colors.css";
import "./globals.css";
import "./styles/responsive.css";
import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
const roboto = Oswald({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.className}`}>
        <div className="container">
          <div className="wrapper">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
